# Generated by Django 4.2.5 on 2023-09-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.SlugField(help_text='Enter the name of the company.', max_length=255, unique=True)),
                ('company_registration_number', models.SlugField(help_text='Enter the registration number of the company.', max_length=255, unique=True)),
                ('company_address', models.TextField(help_text='Enter the address of the company.')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.SlugField(help_text='Enter the name of the department.', max_length=255, unique=True)),
                ('company', models.ForeignKey(help_text='Select the company for the department.', on_delete=django.db.models.deletion.PROTECT, related_name='departments', related_query_name='department', to='core.company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_name', models.SlugField(help_text='Enter the name of the role.', max_length=100, primary_key=True, serialize=False)),
                ('duties', models.TextField(help_text='Enter the duties of the role.')),
                ('department', models.ForeignKey(help_text='Select the department for the role.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='core.department')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(help_text='Enter the name of the employee', max_length=100)),
                ('employee_id', models.CharField(help_text='Enter the ID of the employee', max_length=100, primary_key=True, serialize=False)),
                ('date_started', models.DateField(help_text='Enter the start date of the employee')),
                ('date_left', models.DateField(help_text='Enter the end date of the employee')),
                ('role_name', models.ForeignKey(help_text='Select the role of the employee', on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='core.role')),
            ],
        ),
    ]
