# Generated by Django 4.2.5 on 2023-09-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(help_text='Select the company for the department.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', related_query_name='department', to='core.company'),
        ),
    ]
